### ISSUE TITLE
Differ not formating strings correctly

### ISSUE THREAD

**Issue by zonker** [pvande/differ#1]
The difference between two strings is

Original -- `Hello`
Revision -- `<strong>Hello</strong>`

using diff_by_word and format :html

Result posted below.

Technically, Differ is doing it correctly. The delta change is the `<strong> </strong>` tags.

What I would like to figure out is how to change the output
from: 
    <ins class="differ"><strong></ins>In<ins class="differ"></strong> the</ins>
to:
    <strong><ins class="differ">In</ins></strong> the

Any ideas of where to attack this would be appreciated. It is an awesome gem, just this one problem is driving me batty

thanks

zonker

DIFF:

```
<ins class="differ"><strong></ins>In<ins class="differ"></strong> the</ins> 
<ins class="differ">early 1900s, Freud and a <strong>growing</strong> number
of followers formed a psychoanalytic movement. Carl Gustav Jung
(1875&ndash;1961) and Alfred Adler (1870&ndash;1937) were prominent in
</ins>the <del class="differ">early 1900s, Freud and a growing number of
followers formed a psychoanalytic </del>movement<del class="differ">. Carl
Gustav Jung (1875&ndash;1961) and Alfred Adler (1870&ndash;1937) were
prominent in the movement</del>, but both were independent thinkers, and Freud
apparently had little tolerance for individuals who challenged his ideas.
```

NEW:

```
<strong>In</strong> the early 1900s, Freud and a <strong>growing</strong>
number of followers formed a psychoanalytic movement. Carl Gustav Jung
(1875&ndash;1961) and Alfred Adler (1870&ndash;1937) were prominent in
the movement, but both were independent thinkers, and Freud apparently had
little tolerance for individuals who challenged his ideas.
```

ORIGINAL:

```
In the early 1900s, Freud and a growing number of followers formed a
psychoanalytic movement. Carl Gustav Jung (1875&ndash;1961) and
Alfred Adler (1870&ndash;1937) were prominent in the movement, but
both were independent thinkers, and Freud apparently had little tolerance
for individuals who challenged his ideas.
```

(Edited for formatting and clarity -- pvande)

**Comment by pvande** [comment]
It may not be exactly what you're looking for, but try using `Differ#diff(@new, @old, ' ')`.

```
@old = "I think that this is a great idea."
@new = "<b>I</b> think that <b>this</b> is a great idea."

Differ.diff_by_word(@new, @old)
# => #<Differ::Diff:0x101261fb8 @raw=[{+"<b>"}, "I", {+"</b> think"}, " ", {-"think "}, "that", {+" <b>this</b> is"}, " ", {-"this is "}, "a great idea."]>

Differ.diff(@new, @old, ' ')
# => #<Differ::Diff:0x1012af088 @raw=[{"I" >> "<b>I</b>"}, " think that ", {"this" >> "<b>this</b>"}, " is a great idea."]>
```

**Comment by zonker** [comment]
Hey man,

Thanks for the quick reply. You solution fixed the < > problem but instead of just highlight the change, it showed the whole block as being changed. It works on small text block but not whole paragraphs with html code mixed in.

But, it gave me an idea, and hackage as it may be, it worked. If i just substitute for < and /> for some unique identifier, run it thru Differ and then put the < and </ back, it works like a champ. Well, except is the change is directly in the middle of an HTML code but I can live with that.
(You get something like <a href = <ins class="differ">"some ref"</ins></a>)

I am still too new to Rails to start mucking with your plugin but if you are ever tinkering with it, this worked.

##Substitue < </ for unique identifers

<% @thisPost.gsub!("</", "##/##") %>
<% @thisPost.gsub!("<", "##BEGIN##") %>
<% @thisPost.gsub!(">", "##END##") %>
<% @prevPost.gsub!("</", "##/##") %>
<% @prevPost.gsub!("<", "##BEGIN##") %>
<% @prevPost.gsub!(">", "##END##") %>

<% @diff = Differ.diff_by_word(@thisPost, @prevPost) %>

<% mystring=@diff.to_s %>
<% mystring.gsub!("##/##", "</") %>
<% mystring.gsub!("##BEGIN##", "<") %>
<% mystring.gsub!("##END##", ">") %>

Like I said before, I don't think the problem is Differ itself. It is how GNU diff handles < and >. So subbing them out for something other than < > works. 

And maybe it is just a Mac OS thing. For the record this is running on OS X 10.5.8 with diff (GNU diffutils) 2.8.1

But thanks again for the fast response. It was me trying your suggestion that actually pointed me to my hacky fix.

zonker

**Comment by pvande** [comment]
It seems like what you really want for this is an HTML-aware diff algorithm, which is certainly not impossible, but is not really implemented in the current version of Differ.  If this is something that you feel would have real value to you and others, feel free to file a feature request for it.
