### ISSUE TITLE
Showing only changes?

### ISSUE THREAD

**Issue by pjammer** [pvande/differ#2]
I don't know how to put it, but to be selfish, here's what i want and need to do:

I grab an html page with net/http, and i save it to the Database.
I then compare this page to another page i grabbed, say yesterday.

I only want the changes between the two pages to appear.

Is this gem right for that?  I can see it noticing some changes in the shit i'm looking at, but I don't know how to get it out and use it.  i can see something like this gist https://gist.github.com/caf0aff6c57f9ca011a9

I mean i see {+ where it should be, which is all i want to see printed out.

thoughts?

**Comment by pvande** [comment]
It's not officially supported yet, but you could try something like this in the meantime:

```
require 'differ/string'

class Differ::Diff
  def changes
    @raw.reject { |e| e.is_a? String }
  end
end

changes = ("foo bar baz" - "foo bad baz").changes
```

Official support for this kind of functionality is coming.

It's also worth keeping in mind that doing string diffs of HTML has the potential to result in invalid HTML.  But you probably already knew that.

**Comment by pjammer** [comment]
tbh, in screen scraping, i needed to pull the tag, and the data within the tag.

invalid HTML is ok, as long as i get those two things, as i wasn't going to "use" the actual data to reproduce html... if that makes sense.

mostly i was going to stash the "original" screen scrape and then compare the diff of the latest screen scrape.  (again if that makes sense).  See this .changes method kicks ass, cause then i can run the saved TAG (which i store in the DB) and the data from the tag against this changes... if the DIFF has a change for that tag, then i can compare it against what i have in the DB... if not, i ignore it and go on to the next.

Again, i am pie in the sky thinking, but your gem comes close, and i think it'd be a neat feature, so i look forward to it. thanks for the reply.
